var TextData = {
  goodAdjective: [
    "Amusing",    "ASMR",       "Assorted",     "Battle",     "Black",      "Blue",
    "Bubbling",   "Charm",      "Crystal",      "Data",       "Delightful",
    "Dope",       "Dream",      "Eyeball",      "Fire",       "Flat",
    "Flux",       "Fungus",     "Gas",          "God",        "Grow",
    "Guardian",   "Harmony",    "Holo",         "Important",  "Jeweled",
    "Laser",      "Lovely",     "Mineral",      "Nutrient",   "Parasitic",
    "Passion",    "Phase",      "Planetary",    "Psychic",    "Red",
    "Religious",  "Screech",    "Shimmer",      "Singing",    "Whining"
  ],
  goodPlural: [
    "Ales",       "Babies",     "Balls",        "Baubles",    "Beetles", 
    "Bubbles",    "Chews",      "Cloth",        "Cones",      "Cubes",
    "Cylinders",  "Devices",    "Drones",       "Eggs",       "Enzymes",
    "Furs",       "Gems",       "Goos",         "Grids",      "Harps",
    "Inductors",  "Isotopes",   "Juices",       "Jumpers",    "Keys",
    "Knives",     "Masks",      "Orbs",         "Pearls",     "Pets",
    "Pods",       "Probes",     "Pumps",        "Pyramids",   "Rings",
    "Rods",       "Secrets",    "Slugs",        "Spices",     "Stones",
    "Tagines",    "Tasties",    "Teleporters",  "Things",     "Transmitters",
    "Tureens",    "Vids"
  ],
  goodSingular: [
    "Ale",        "Baby",       "Ball",         "Bauble",     "Beetle",
    "Bubble",     "Chew",       "Cloth",        "Cone",       "Cube",
    "Cylinder",   "Device",     "Drone",        "Egg",        "Enzyme",
    "Fur",        "Gem",        "Goo",          "Grid",       "Harp",
    "Inductor",   "Isotope",    "Juice",        "Jumper",     "Key",
    "Knife",      "Mask",       "Orb",          "Pearl",      "Pet",
    "Pod",        "Probe",      "Pump",         "Pyramid",    "Ring",
    "Rod",        "Secret",     "Slug",         "Spice",      "Stone",
    "Tagine",     "Tasty",      "Teleporter",   "Thing",      "Transmitter",
    "Tureen",     "Vid"
  ],
  pirateNames: [
    "Hungry Hungry",            "Men's Health",             "Subprime Lender",
    "Cost Of Doing Business",   "High Deductible",          "Break Even",
    "Death and Gravity",        "Dramatic Exit",            "Ethics Gradient",
    "Honest Mistake",           "Killing Time",             "Lasting Damage",
    "Profit Margin",            "Reasonable Excuse",        "Trade Surplus",
    "Uninvited Guest",          "Wit Amidst Folly",         "Appropriate Measures",
    "Excessive Tolerance",      "Frank Exchange of Ideas",  "Vindictive Euphemism",
    "Polite Invitation",        "Bad for Business",         "Hidden Income",
    "Just Testing",             "Lapsed Pacifist",          "Insurance Claim",
    "Shrinkage",                "Shoot Them Later",         "So Much For Subtlety",
    "Somebody Else's Problem",  "Steely Glint",             "Unwitting Accomplice",
    "Youthful Indiscretion",    "Forgetful",                "Target Practice",
    "Uncertain Doom",           "Second Guess",             "Lower Your Shields",
    "Last Chance",              "Breakneck Pace",           "At All Cost",
    "Business End",             "Shoots First",             "Short End",
    "Cargo Liberator",          "Cash Money",               "Unfriendly",
    "Special Blend",            "Stop Your Wailing",        "Make Your Peace",
    "Wild Abandon",             "Why Worry",                "Better Luck Next Time",
    "Dumb Luck",                "Meant Well",               "Nevermore",
    "Bad News",                 "Why Don't She Write",      "Inopportune Moment",
    "Carpe Per Diem",           "Imagine That",             "Priceless Expression",
    "Dicey Odds",               "New Economy",              "Infringer",
    "Pot Luck",                 "One Too Many",             "Bad Medicine",
    "Free Lunch",               "Losing Bet",               "Shakedown",
    "Sudden Movement",          "Miranda Right",            "Imaginative Name",
    "Stand and Deliver",        "Long Walk, Short Airlock", "Despicable",
    "Oh No", "Baleful",         "Unimaginable Delight",     "Day Is Ours",
    "Faster Than It Looks",     "Relentless Apathy",        "Doth Protest Too Much",
    "Coming Right At Us",       "End Of The Line",          "Minor Anomaly",
    "Launch On Warning",        "Collective Endeavor",      "Bad Gravity",
    "Flux Capacitor",           "Gray Area",                "Inevitable",
    "Line Item Veto",           "Inescapable Questioner",   "Trade By Other Means",
    "Personal Growth Area",     "Probable Cause",           "Stop And Frisk",
    "Free Stress Test",         "Incorrigible"
  ],
  contractTerms: [
    "Known Knowns",               "Unknown Unknowns",         "Base Outlay",
    "Service Charge",             "Danger Assessment",        "Official Beeswax",
    "Beekeeper Room and Board",   "Mood Lighting",            "Organic Minibar",
    "Beehive Travel Insurance",   "Bee Chow",                 "Hydroponic Clover",
    "Hood Ornament Polish",       "Depollenization Process",  "Anti-Pirate Ammunition",
    "Training Video License",     "Conscription Fee",         "Ointment, 64oz. tublet",
    "Printer Ink",                "Computer Paper",           "Dry Cleaning Fee",
    "Ceremonial Orbs",            "Side Dishes"
  ],
  sectorTitle: [
    "Aglaonike",    "Alhazen",    "al-Fazari",  "al-Khwarizmi",   "Al-Biruni",
    "Khojandi",     "Ptolemy",    "Gautama",    "Bhaskara",       "Madhava",
    "Aryabhata",    "Kepler",     "Cassini",    "Nebra",          "Barnard",
    "Nabonassar",   "Messier",    "Verrier",    "Brahmagupta",    "Chandrasekhar",
    "Sagan",        "Hypatia"
  ],
  sectorSubtitle: [
    "Expanse",      "Rift",       "Arm",        "Belt",     "Region",
    "Zone",         "Field",      "Triangle",   "Reach",    "Verge",
    "Cluster",      "Alpha",      "Beta",       "Gamma",    "Delta",
    "Epsilon",      "Zeta",       "Eta",        "Theta",    "Iota",
    "Kappa",        "Lambda",     "Mu",         "Nu",       "Xi",
    "Omicron",      "Pi",         "Rho",        "Sigma",    "Tau",
    "Upsilon",      "Phi",        "Chi",        "Psi",      "Omega"
  ]
};

module.exports = TextData;
